name: dev_tokoemasusman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  get: 4.6.6
  intl: ^0.19.0
  sizer: ^2.0.15
  supercharged: ^2.1.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: MontserratR
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratM
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratB
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
